### ISSUE TITLE
zero stop code first cycle

### ISSUE THREAD

**Issue by schiebel** [casangi/casagui#32]
The first cycle attempted always appears to exit with a "Zero stop code" and without any iterations, even when `niter` and `threshold` are set. The logs show that the threshold in `deconvolve` is set high in "step 3" so that could explain why it is stopping without any iterations. The issue is fixed however when running the succeeding cycles.

**Comment by Kitchi** [comment]
Hey @schiebel - I'm not able to reproduce this issue.  When I launch a new run of iclean, it does show "zero stop code" but it appears to run iterations as expected. The "zero stop code" is because it hits the stopping criteria because of `cycleniter` and not any of the other "major" stopping criteria (`nmajor`, `niter`, `threshold` etc.)

Can you check if you're still able to reproduce this error?

**Comment by schiebel** [comment]
Hi @Kitchi Sorry it took a while for me to get all of my ducks in a row to respond.

I have pushed up all of my changes (even though the `createregsion` app is still a work in progress) because I wanted to make sure that we're able to look at the same code. The new `casa-CAS-14283-8-py3.10.el8.tar.xz` tarball can be used with the `v0.3.110` casagui wheel. Python 3.10 is now **required** and Bokeh >= 3.5 is used.

When I run a single iteration with the single arrow button and `nmajor` set to one I see:
<img width="533" alt="Screen Shot 2024-11-08 at 4 38 36 PM" src="https://github.com/user-attachments/assets/a257cd19-601f-4ddc-a20e-a0f351b4e433">
the "_Reached the major cycle limit (nmajor)_" message seems great.

When I run a single iteration with the single arrow button and `nmajor` set to **three** I see:
<img width="533" alt="Screen Shot 2024-11-08 at 4 41 57 PM" src="https://github.com/user-attachments/assets/a0538f63-dc5a-40c9-9b7d-28117b94fb29">
with "_Zero stop code_" which needs to be improved. I don't know if it makes the most sense for this to be done in `gclean` or within the frontend... but in general for headless testing it is nice to push everything possible down into `gclean`.

At least I **believe**, this is what this ticket is about...   :smile:

**Comment by Kitchi** [comment]
Thanks @schiebel! That helps. I initially understood the bug to be that zero iterations were run even though they should be, but I wasn't able to reproduce that. Glad to see that this isn't the case for you either.

The "zero stop code" return value happens because `cycleniter` is set to some small value (default is 10) and after 10 iterations on a single plane, it ceases to iterate regardless of any global stopping criteria (like number of major cycles). As of now, there is no stopcode for "reached cycleniter" in tclean, and hence not in gclean either. 

What I can do is implement a new stopcode specifically for gclean for cycleniter, which should improve the error message you're seeing here. I'll give that a go and push it into `CAS-13581`.

**Comment by Kitchi** [comment]
@schiebel  The latest commit to `CAS-14283` solves this issue. I've assigned `stopcode=11` and `stopDescription = 'Reached the cycle iteration limit'` to the `cycleniter` stopping criterion. The logic for using 11 is explained in the commit message.

I've tested this out, and it appears to work fine. Let me know if it fixes the issue you're seeing as well. I'm closing the issue for now, but in case it's not resolved I'll re-open it and debug.

**Comment by schiebel** [comment]
Hi @Kitchi Unfortunately, I still see the same issue. When I:

1. when I set `nmajor` to 1 and `niter` to some large number I receive from `gclean` a *stopdesc* of "Reached the major cycle limit (nmajor)" and a *stopcode* of 9
2. when I set `nmajor` to 3 and `niter` to some large number I receive from `gclean` a *stopdesc* of "" and a `stopcode` of 0

After my last post, I started wondering if `gclean` needs more information about what the user has selected to properly generate a return string, i.e. which button (either one major cycle or a sequence of major cycles) has been selected by the user.

**Comment by Kitchi** [comment]
@schiebel  - I've pushed a bugfix to the branch now. let me know if this resolves it for you as well.  It seems to have done for me.  The issue was an unrelated bug, but it's been squashed now. The bug was that `deconvolve` was running iterations before the GUI popped up, so when the user set a mask and asked to run a major cycle, the image is already at or close to the defined threshold so it ends up running zero or one iterations the first time around. 

`gclean` should be agnostic to whether the user requested one or many major cycles, because the convergence criteria are identical. I think the setup now is the most general way to structure it, i.e., the front end calls gclean one major cycle at a time and checks for convergence after each one.

**Comment by schiebel** [comment]
Hi @Kitchi this still happens for me... I'll follow up in chat...
